### ISSUE TITLE
Issue with mimo_inference.py: No Iteration Progress (0it [00:00, ?it/s])

### ISSUE THREAD

**Issue by aomenfage** [XZWY/SpatialCodec#1]
Hello,

I've been trying to run the mimo_inference.py script from the SpatialCodec repository but encountered an issue where the script doesn't seem to progress through iterations. Below are the details of my execution command and the resulting output.

`Python ./SpatialCodec/mimo_inference.py --input_dir intro.wav --ref_ckpt_dir ref_subband_codec_ckpt --spatial_ckpt_dir SpatialCodec_ckpt --output_dir output.wav`

The script should process the input file (intro.wav) and output the result in output.wav.
The script starts but immediately shows the following output and doesn't progress further:

`0it [00:00, ?it/s]`

I suspect this might be related to either the input data not being correctly loaded or an issue in the iteration process of the script. I would appreciate any guidance or suggestions to resolve this issue.

**Comment by XZWY** [comment]
oh, input_dir and output_dir should be directories, input_dir should contain all the .wav files you want to process and the result .wav files are saved in the output_dir

**Comment by aomenfage** [comment]
> oh, input_dir and output_dir should be directories, input_dir should contain all the .wav files you want to process and the result .wav files are saved in the output_dir

Thank you very much, it works. But I have another problem when I run the code.

 File "./SpatialCodec/mimo_inference.py", line 117, in <module>
    c_emb = encoder(cov) # bs, 9*512, n_frames
  File "/home/sc/miniconda3/envs/zxy_spatial/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/mnt/4t/code_space/zxy/SpatialCodec-main/SpatialCodec/spatial_model_subband.py", line 106, in forward
    x = self.conv_list[i](x)
  File "/home/sc/miniconda3/envs/zxy_spatial/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/sc/miniconda3/envs/zxy_spatial/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 446, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/sc/miniconda3/envs/zxy_spatial/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 442, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Given groups=1, weight of size [64, 74, 3, 5], expected input[1, 44, 3001, 321]

I use a wav file with 6 channels. It seems that the channel of the audio file was wrong. Thank you for your assistance.

**Comment by XZWY** [comment]
yes, the model takes 8-channel outputs, and is only trained on one array configuration, as mentioned in the paper

**Comment by aomenfage** [comment]
> yes, the model takes 8-channel outputs, and is only trained on one array configuration, as mentioned in the paper

thank you
