### ISSUE TITLE
Training code

### ISSUE THREAD

**Issue by sivannavis** [XZWY/SpatialCodec#3]
Hi! Could you provide the training code for the model? Thanks!

**Comment by XZWY** [comment]
sorry, that code is still not organized in a private repo, I could send you by email if needed, but the dataset is not accessible

**Comment by lixinghe1999** [comment]
@XZWY 
Dear authors, 
Can you send the training code to helixing99@gmail.com? It is really beneficial to take it as a reference.
Thanks!

**Comment by XZWY** [comment]
Sure, below is the code base, the rough doc is here:
https://docs.google.com/document/d/1w-y4s5ykvhipnlIs7ampnuIzi3LXpDaewCu-O6tAvmo/edit?usp=sharing.
Seems only EXP4 and EXP5 are most important as in paper, and you could
probably check from the mc_start.sh file to find what each experiment is
training. Sorry for the messy codes.....Good luck!
 SpatialCodec-main.zip
<https://drive.google.com/file/d/1WsjbPRhVCPCBB0I_fDWU-xTj03ub8e5R/view?usp=drive_web>

Best,
Zhongweiyang Xu
